.eslintrc.json, .gitignore, README.md, functions/getTestTypes.js, handler.js, models/HTTPResponseStatus.js, offline/migrations/test-types.json, package-lock.json, package.json, serverless.yml, services/testTypesService.js, tests/integration/testTypesService.intTest.js, tests/unit/testTypesService.unitTest.js
* Created test types microservice. 
* Implemented functionality to fetch test types from dynamodb. 
* Wrote integration and unit tests. 
* Configured configuration in configurations. 
* Added 1 mock test type in the migrations folder for the database to be populated. This test type DOES NOT REFLECT the way a test type should look like. Confirmation on whether real data should be used will come soon, and I'll update the migration file with real data once 
Jira ticket [here](https://jira.i-env.net/browse/CVSB-386)
=> CVSB-386 - Test Types microservice

tests/resources/test-types.json
* Changed test types json to match the taxonomy
=> CVSB-1315-2

package-lock.json, package.json, serverless.yml, src/models/TestTypesDAO.js
=> CVSB-4794 add XRay integrations. Tests all pass locally.

tests/resources/test-types.json
=> CVSB-4068 updated forVehicleAxles for id:29

tests/integration/getTestTypesByIdFunction.intTest.ts, tests/resources/test-types.json
~~PR will be merged and tested in 6426~~
This change is not required for MVP and it will be merged into develop after 6426 has been released
=> CVSB-8109 Added test types to 5+ axles vehicles

tests/resources/test-types.json
Changed testTypeId for free loaded retest
https://jira.dvsacloud.uk/browse/CVSB-17868
=> CVSBB-17868 - changed test type id for free loaded retest

gulpfile.js, package-lock.json, package.json
https://jira.dvsacloud.uk/browse/CVSB-19400
=> chore(cvsb-19400): fix npm vulnerabilities

package-lock.json, package.json
[VTA-505](https://jira.dvsacloud.uk/browse/VTA-505)
=> VTA-568: Resolve high vulnerabilities (#117)

src/models/ITestType.ts, tests/unit/getTestTypesByIDFunction.unitTest.ts
This PR includes the changes required to allow a vehicle configuration of 'long semi-trailer', as per option 1 on Jira ticket.
[VTA-761](https://dvsa.atlassian.net/browse/VTA-761)
=> VTA-761: Update VTA BE APIs to cater for long semi-trailer vehicle configuration

src/assets/Enums.ts, src/functions/getTestTypesById.ts, src/models/HTTPError.ts, src/models/TestTypesDAO.ts, src/utils/Validator.ts, tests/integration/getTestTypesByIdFunction.intTest.ts, tests/unit/getTestTypesByIDFunction.unitTest.ts
Merge from holding branch VTADEV-31 into develop
[VTA-696](https://dvsa.atlassian.net/browse/VTA-696)
=> VTA-696: Add validation for parameters and additional request/response logging

tests/resources/test-types.json
Remove invalid test code item for id 414 vehicle class 'trl'.
[CB2-6941](https://dvsa.atlassian.net/browse/CB2-6941)
=> fix(cb2-6550): remove invalid testType taxonomy item

tests/resources/test-types.json
VTG10 Notifiable Alteration with MR only has the wrong test code
[CB2-6949](https://dvsa.atlassian.net/browse/CB2-6949)
=> fix(cb2-6949): change test code

package-lock.json, package.json, tests/resources/test-types.json, tests/unit/getTestTypesFunction.unitTest.ts
PR to add 2 extra light vehicle tests to taxonomy, and push into vtmdev-1 for testing
[CB2-7005](https://dvsa.atlassian.net/browse/CB2-7005)
Also bumps node-yaml and js-yaml to fix vulnerabilities
=> feat(cb2-7005): light vehicle hierarchy

docs/test-types-api.yml, src/models/ITestType.ts
[CB2-397](https://dvsa.atlassian.net/browse/CB2-397)
=> feat(cb2-7397): add the new vehicle type

tests/resources/test-types.json
Create a HGV Type Approved Tractor Unit DBA
Add ADR test type
[Link](https://dvsa.atlassian.net/browse/CB2-7541)
=> feature(cb2-7537): create a hgv type approved tractor unit dba

tests/resources/test-types.json
add a new IVA test type for car and LGV
[CB2-7533](https://dvsa.atlassian.net/browse/CB2-7533)
=> feat(cb2-7533): add new IVA test type for car and lgv

package-lock.json, package.json, patches/dynamodb-localhost+0.0.9.patch
Fixes integration tests. DynamoDB local had an update which increased validation around aws keys. quick fix to be able to deploy services.
[link to ticket number]()
=> fix(cb2-0000): fix integration tests

.github/workflows/openapi-gen.yml
Regenerate API services automatically
[CB2-8130](https://dvsa.atlassian.net/browse/CB2-8130)
=> feature(cb2-8130): regenerate API services automatically

.github/workflows/pr-checks.yml, package-lock.json, package.json, src/services/TestTypesService.ts, tests/unit/configuration.unitTest.ts, tests/unit/testTypesService.unitTest.ts
Update to include Sonar Scanner NPM
One line description
[CB2-10091](https://dvsa.atlassian.net/browse/CB2-10091)
=> feat(cb2-10091): update to include sonar scanner

.snyk, tests/resources/test-types.json
One line description
[link to ticket number]()
=> feat(cb2-11238): show test types 105 and 68 for provisional records

tests/resources/test-types.json
Failed MSVA tests trigger the generation of an MSVA 30 certificate PDF
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-10738)
=> feat(CB2-10738): msva with certificate
